/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  html: [
    {
      type: "category",
      label: "HTML",
      collapsible: false,
      link: {
        type: "generated-index",
        slug: "/html",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "html",
        }
      ]
    }],
  css: [
    {
      type: "category",
      label: "CSS",
      collapsible: false,
      link: {
        type: "generated-index",
        slug: "/css",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "css",
        }
      ]
    }

  ],
  js: [
    {
      type: "category",
      label: "JavaScript",
      collapsible: false,
      link: {
        type: "generated-index",
        slug: "/js",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "js",
        }
      ]
    }

  ],
  vue: [
    {
      type: "category",
      label: "Vue",
      collapsible: false,
      link: {
        type: "generated-index",
        slug: "/vue",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "vue",
        }
      ]
    }

  ],
  vue3: [
    {
      type: "category",
      label: "Vue3",
      collapsible: false,
      link: {
        type: "generated-index",
        slug: "/vue3",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "vue3",
        }
      ]
    }

  ],
  ts: [
    {
      type: "category",
      label: "TypeSript",
      collapsible: false,
      link: {
        type: "generated-index",
        slug: "/ts",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "ts",
        }
      ]
    }

  ],
  react: [
    {
      type: "category",
      label: "React",
      link: {
        type: "generated-index",
        slug: "/react",
      },
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "react",
        }
      ]
    },

  ],
  nodejs: [
    {
      type: "category",
      label: "NodeJS",
      collapsible: false,
      link: {
        type: "generated-index",
        slug: "/nodejs",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "nodejs",
        }
      ]
    }
  ],
  webpack: [
    {
      type: "category",
      label: "WebPack",
      collapsible: false,
      link: {
        type: "generated-index",
        slug: "/webpack",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "webpack",
        }
      ]
    }
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
