/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  html: [
    {
      // type: "autogenerated",
      // // dirName: "javascript",
      // type: "category",
      // label: "HTML",
      // link: { type: "doc", id: "html/index" },
      // collapsible: false,
      // items: [
      //   {
      //     type: "category",
      //     label: "基础",
      //     link: {
      //       type: "generated-index",
      //     },
      //     items: [
      //       {
      //         type: "autogenerated",
      //         dirName: "html/基础", // '.' 即当前的文档文件夹
      //       },
      //     ],
      //   },
      // ]
      type: "category",
      label: "HTML",
      collapsible: false,
      link: { type: "doc", id: "html/index" },
      items: [
        {
          type: "autogenerated",
          dirName: "html",
        }
      ]
    }],
  css: [
    {
      type: "category",
      label: "CSS",
      collapsible: false,
      link: { type: "doc", id: "css/index" },
      items: [
        {
          type: "autogenerated",
          dirName: "css",
        }
      ]
    }

  ],
  js: [
    {
      type: "category",
      label: "JavaScript",
      collapsible: false,
      link: { type: "doc", id: "js/index" },
      items: [
        {
          type: "autogenerated",
          dirName: "js",
        }
      ]
    }

  ],
  vue: [
    {
      type: "category",
      label: "Vue",
      collapsible: false,
      link: { type: "doc", id: "vue/index" },
      items: [
        {
          type: "autogenerated",
          dirName: "vue",
        }
      ]
    }

  ],
  vue3: [
    {
      type: "category",
      label: "Vue3",
      collapsible: false,
      link: { type: "doc", id: "vue3/index" },
      items: [
        {
          type: "autogenerated",
          dirName: "vue3",
        }
      ]
    }

  ],
  ts: [
    {
      type: "category",
      label: "TypeSript",
      collapsible: false,
      link: { type: "doc", id: "ts/index" },
      items: [
        {
          type: "autogenerated",
          dirName: "ts",
        }
      ]
    }

  ],
  react: [
    {
      type: "category",
      label: "React",
      collapsible: false,
      link: { type: "doc", id: "react/index" },
      items: [
        {
          type: "autogenerated",
          dirName: "react",
        }
      ]
    }
  ],
  nodejs: [
    {
      type: "category",
      label: "NodeJS",
      collapsible: false,
      link: { type: "doc", id: "nodejs/index" },
      items: [
        {
          type: "autogenerated",
          dirName: "nodejs",
        }
      ]
    }
  ],
  webpack: [
    {
      type: "category",
      label: "WebPack",
      collapsible: false,
      link: { type: "doc", id: "webpack/index" },
      items: [
        {
          type: "autogenerated",
          dirName: "webpack",
        }
      ]
    }
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
